// sidebarsAdm.js
/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebarsAdm = {
  api: [
    {
      type: "autogenerated",
      dirName: ".",
    },
  ],
};

module.exports = sidebarsAdm;
